import tkinter as tk
from tkinter import ttk, messagebox, filedialog

# ---------------------------
# SystemVerilog generation utilities
# ---------------------------
def sv_port_decl(name, direction, dtype, width, signed, custom_range):
    """
    Build a single SystemVerilog port declaration line.

    name         : str, port name
    direction    : 'in' | 'out' | 'inout'
    dtype        : 'logic' | 'wire' | 'bit'
    width        : int >= 1 (used only if custom_range is empty)
    signed       : bool
    custom_range : str like "[N-1:0]" or "" to auto-generate from width
    """
    dir_kw = {"in": "input", "out": "output", "inout": "inout"}[direction]
    dtype_kw = dtype.strip()
    signed_kw = " signed" if signed else ""

    # Determine packed dimension
    rng = custom_range.strip()
    if rng:
        # Assume user typed a valid packed dimension, e.g., [N-1:0]
        if not (rng.startswith('[') and rng.endswith(']')):
            # Try to be helpful: wrap if missing brackets
            rng = f"[{rng}]"
        packed = f"{rng} "
    else:
        if width > 1:
            packed = f"[{width-1}:0] "
        else:
            packed = ""

    # Final declaration (ANSI style)
    # Example: "    input logic signed [7:0] data_in"
    return f"    {dir_kw} {dtype_kw}{signed_kw} {packed}{name}"

def generate_sv_module(module_name, ports, add_header=True, add_footer=True):
    """
    Generate a SystemVerilog module with ANSI-style port declarations.

    module_name : str
    ports       : list of dicts with keys:
                  name, dir ('in'|'out'|'inout'), type ('logic'|'wire'|'bit'),
                  width (int), signed (bool), range (str)
    add_header  : include header comments and optional pragmas
    add_footer  : include endmodule with name

    Returns a single string of the module.
    """
    clean_name = module_name.strip() or "my_module"

    if not ports:
        # module with no ports
        body = (
            (("// SystemVerilog module generated by SV Port Generator\n"
              "// Fill in your implementation below\n") if add_header else "") +
            f"module {clean_name} ();\n\n"
            f"  // TODO: implement\n\n"
            f"endmodule : {clean_name}\n"
        )
        return body

    decls = [
        sv_port_decl(p['name'], p['dir'], p['type'], p['width'], p['signed'], p['range'])
        for p in ports
    ]
    port_block = ",\n".join(decls)

    header = ""
    if add_header:
        header = (
            "`default_nettype none\n\n"
        )

    footer = f"\n`default_nettype wire\n" if add_footer else ""

    module = (
        header +
        f"module {clean_name} (\n{port_block}\n);\n\n"
        f"endmodule \n" +
        footer
    )
    return module

# ---------------------------
# GUI: Table widget to manage ports
# ---------------------------
class PortTable(ttk.Frame):
    def __init__(self, master):
        super().__init__(master)

        # Treeview columns
        self.tree = ttk.Treeview(
            self,
            columns=("name","dir","type","width","signed","range"),
            show="headings",
            height=10
        )
        headings = [
            ("name",   160),
            ("dir",     70),
            ("type",   100),
            ("width",   70),
            ("signed",  70),
            ("range",  140),
        ]
        for col, w in headings:
            self.tree.heading(col, text=col.upper())
            self.tree.column(col, width=w, anchor="w")
        self.tree.grid(row=0, column=0, columnspan=5, sticky="nsew")

        # Scrollbar
        yscroll = ttk.Scrollbar(self, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscroll=yscroll.set)
        yscroll.grid(row=0, column=5, sticky="ns")

        # Form fields
        self.name_var = tk.StringVar()
        self.dir_var = tk.StringVar(value="in")
        self.type_var = tk.StringVar(value="logic")
        self.width_var = tk.StringVar(value="1")
        self.signed_var = tk.BooleanVar(value=False)
        self.range_var = tk.StringVar(value="")  # e.g., "[N-1:0]"

        # Row 1
        ttk.Label(self, text="Name").grid(row=1, column=0, sticky="w", padx=2, pady=4)
        ttk.Entry(self, textvariable=self.name_var, width=20).grid(row=1, column=1, sticky="we", padx=2)

        ttk.Label(self, text="Dir").grid(row=1, column=2, sticky="w", padx=2)
        ttk.Combobox(self, textvariable=self.dir_var,
                     values=["in","out","inout"], width=7, state="readonly").grid(row=1, column=3, sticky="we", padx=2)

        ttk.Label(self, text="Type").grid(row=1, column=4, sticky="w", padx=2)
        ttk.Combobox(self, textvariable=self.type_var,
                     values=["logic","wire","bit"], width=10, state="readonly").grid(row=1, column=5, sticky="we", padx=2)

        # Row 2
        ttk.Label(self, text="Width").grid(row=2, column=0, sticky="w", padx=2)
        ttk.Entry(self, textvariable=self.width_var, width=10).grid(row=2, column=1, sticky="we", padx=2)

        ttk.Checkbutton(self, text="Signed", variable=self.signed_var).grid(row=2, column=2, sticky="w", padx=2)

        ttk.Label(self, text="Packed Range (opt)").grid(row=2, column=3, sticky="w", padx=2)
        ttk.Entry(self, textvariable=self.range_var, width=18).grid(row=2, column=4, sticky="we", padx=2)
        ttk.Label(self, text="Ex: [N-1:0]").grid(row=2, column=5, sticky="w", padx=2)

        # Buttons
        ttk.Button(self, text="Add / Update", command=self.add_or_update).grid(row=3, column=0, padx=2, pady=6, sticky="we", columnspan=2)
        ttk.Button(self, text="Delete", command=self.delete_selected).grid(row=3, column=2, padx=2, pady=6, sticky="we")
        ttk.Button(self, text="Clear", command=self.clear_all).grid(row=3, column=3, padx=2, pady=6, sticky="we")

        self.grid_rowconfigure(0, weight=1)
        self.grid_columnconfigure(1, weight=1)
        self.grid_columnconfigure(4, weight=1)

        # Selecting a row loads it into the editor
        self.tree.bind("<<TreeviewSelect>>", self.on_select)
        self.tree.bind("<Button-1>", self._on_tree_click, add="+")

    # Add this method inside PortTable
    def _on_tree_click(self, event):
        # If click is on empty area, clear selection and editor
        row = self.tree.identify_row(event.y)
        if row == "":
            self.tree.selection_remove(self.tree.selection())
            self._clear_editor()
    
    def _clear_editor(self):
        self.name_var.set("")
        self.dir_var.set("in")
        self.type_var.set("logic")
        self.width_var.set("1")
        self.signed_var.set(False)
        self.range_var.set("")



    def on_select(self, _evt):
        items = self.tree.selection()
        if not items:
            return
        vals = self.tree.item(items[0], "values")
        self.name_var.set(vals[0])
        self.dir_var.set(vals[1])
        self.type_var.set(vals[2])
        self.width_var.set(vals[3])
        self.signed_var.set(vals[4].lower() in ("true","1","yes","y"))
        self.range_var.set(vals[5])

    def add_or_update(self):
        name = self.name_var.get().strip()
        dir_ = self.dir_var.get().strip()
        typ = self.type_var.get().strip()
        width_str = self.width_var.get().strip()
        signed = bool(self.signed_var.get())
        rng = self.range_var.get().strip()

        if not name:
            messagebox.showerror("Validation", "Port name is required.")
            return

        # Width must be a positive integer; used only if custom range is empty
        try:
            width = int(width_str)
            if width < 1:
                raise ValueError
        except ValueError:
            messagebox.showerror("Validation", "Width must be a positive integer.")
            return

        # Update if selected, else add
        vals = (name, dir_, typ, str(width), "True" if signed else "False", rng)
        items = self.tree.selection()
        if items:
            self.tree.item(items[0], values=vals)
        else:
            self.tree.insert("", "end", values=vals)

    def delete_selected(self):
        for item in self.tree.selection():
            self.tree.delete(item)

    def clear_all(self):
        for item in self.tree.get_children():
            self.tree.delete(item)

    def get_ports(self):
        rows = []
        for item in self.tree.get_children():
            name, dir_, typ, width, signed, rng = self.tree.item(item, "values")
            rows.append({
                "name": name,
                "dir": dir_,
                "type": typ,
                "width": int(width),
                "signed": signed.lower() in ("true","1","yes","y"),
                "range": rng
            })
        return rows

# ---------------------------
# Main App
# ---------------------------
class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("SystemVerilog Port Generator")
        self.geometry("900x600")

        # Module name
        top = ttk.Frame(self)
        top.pack(fill="x", padx=10, pady=6)
        ttk.Label(top, text="Module Name:").pack(side="left")
        self.module_var = tk.StringVar(value="my_module")
        ttk.Entry(top, textvariable=self.module_var, width=30).pack(side="left", padx=6)

        # Port table
        self.table = PortTable(self)
        self.table.pack(fill="both", expand=True, padx=10, pady=6)

        # Output + controls
        bottom = ttk.Frame(self)
        bottom.pack(fill="x", padx=10, pady=6)
        ttk.Button(bottom, text="Generate SV", command=self.generate).pack(side="left")
        ttk.Button(bottom, text="Save...", command=self.save).pack(side="left", padx=6)

        # Output text area
        self.output = tk.Text(self, height=14, wrap="none")
        self.output.pack(fill="both", expand=False, padx=10, pady=6)

        # Helpful defaults
        self._seed_example_ports()

    def _seed_example_ports(self):
        # Pre-populate a few typical ports (you can delete them)
        sample = [
            ("clk",     "in",    "logic", 1, False, ""),
            ("rst_n",   "in",    "logic", 1, False, ""),
            ("data_i",  "in",    "logic", 8,  False, ""),
            ("valid_i", "in",    "logic", 1, False, ""),
            ("ready_o", "out",   "logic", 1, False, ""),
            ("data_o",  "out",   "logic", 8,  False, ""),
        ]
        for name, dir_, typ, width, signed, rng in sample:
            self.table.tree.insert("", "end", values=(name, dir_, typ, str(width), "True" if signed else "False", rng))

    def generate(self):
        module = self.module_var.get().strip()
        ports = self.table.get_ports()
        text = generate_sv_module(module, ports)
        self.output.delete("1.0", tk.END)
        self.output.insert("1.0", text)

    def save(self):
        self.generate()
        text = self.output.get("1.0", tk.END).strip()
        if not text:
            messagebox.showinfo("Info", "Nothing to save. Generate first.")
            return
        path = filedialog.asksaveasfilename(defaultextension=".sv",
                                            filetypes=[("SystemVerilog","*.sv"), ("All files","*.*")])
        if path:
            try:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(text + "\n")
                messagebox.showinfo("Saved", f"Saved to {path}")
            except Exception as e:
                messagebox.showerror("Error", f"Failed to save:\n{e}")

if __name__ == "__main__":
    App().mainloop()

